apiVersion: v1
kind: Service
metadata:
  name: modoki-app-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: modoki-app-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modoki-app-pod
  name: modoki-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modoki-app-pod
  template:
    metadata:
      labels:
        app: modoki-app-pod
    spec:
      containers:
      - image: IMAGE_NAME
        imagePullPolicy: Always
        name: server
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: modoki-app-ing
spec:
  rules:
  - host: XXX.apps.tsuzu.xyz
    http:
      paths:
      - backend:
          serviceName: modoki-app-svc
          servicePort: 80
        path: /
  tls:
  - hosts:
    - XXX.apps.tsuzu.xyz
    secretName: modoki-apps-cert-secret