apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: modoki
bases:
  - https://github.com/modoki-paas/modoki-k8s/kubernetes
secretGenerator:
  - name: modoki-api-key
    env: api-key.txt
    type: Opaque
  - name: modoki-db-secret
    env: db.txt
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
