apiVersion: apps/v1
kind: Deployment
metadata:
  name: modoki-apiserver-deployment
  namespace: modoki
  labels:
    app: modoki-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modoki-apiserver
  template:
    metadata:
      labels:
        app: modoki-apiserver
    spec:
      serviceAccountName: modoki-apiserver-sa
      containers:
        - name: modoki-apiserver
          imagePullPolicy: Always
          image: modokipaas/modoki-k8s
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /etc/modoki
              name: config
          resources:
            limits: # ここで制限を指定
              cpu: "1"
              memory: 100Mi
    volumes:
      - name: config
        configMap:
          name: modoki-apiserver-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: modoki-apiserver-config
  namespace: modoki
data:
  apiserver.yaml: |
    db: modoki-db-svc
    endpoints:
      generator:
        endpoint: modoki-yamler-svc
        insecure: true
---
apiVersion: v1
kind: Service
metadata:
  name: modoki-apiserver-svc
  namespace: modoki
spec:
  selector:
    app: modoki-apiserver
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: modoki-apiserver-sa
  namespace: modoki
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: modoki-apiserver-crb
subjects:
  - kind: ServiceAccount
    name: modoki-apiserver-sa
    namespace: modoki
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
