apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: modoki-ingress
  namespace: modoki
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  tls:
    - hosts:
        - apps.tsuzu.xyz
      secretName: apps-tsuzu-xyz-tls
  rules:
    - host: apps.tsuzu.xyz
      http:
        paths:
          - path: /
            backend:
              serviceName: modoki-svc
              servicePort: 80
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: modoki
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: example@example.com
    privateKeySecretRef:
      name: letsencrypt
    dns01:
      providers:
        - name: cf-dns
          cloudflare:
            email: example@example.com
            apiKeySecretRef:
              name: cloudflare-api-key
              key: api-key.txt
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: modoki-apps-cert
  namespace: modoki
spec:
  secretName: modoki-apps-cert-secret
  issuerRef:
    name: letsencrypt
  commonName: "*.apps.tsuzu.xyz"
  dnsNames:
    - apps.tsuzu.xyz
  acme:
    config:
      - dns01:
          provider: cf-dns
        domains:
          - "*.apps.tsuzu.xyz"
          - apps.tsuzu.xyz
