apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: modoki
resources:
  - apiserver.yaml
  - authserver.yaml
  - yamler.yaml
  - ingress.yaml
  - namespace.yaml
  - gateway.yaml
