apiVersion: apps/v1
kind: Deployment
metadata:
  name: modoki-yamler-deployment
  namespace: modoki
  labels:
    app: modoki-yamler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modoki-yamler
  template:
    metadata:
      labels:
        app: modoki-yamler
    spec:
      serviceAccountName: modoki-yamler-sa
      containers:
        - name: modoki-yamler
          imagePullPolicy: Always
          image: modokipaas/modoki-yamler
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /etc/modoki
              name: config
          envFrom:
            - secretRef:
                name: modoki-api-key
          resources:
            limits: # ここで制限を指定
              cpu: "1"
              memory: 100Mi
      volumes:
        - name: config
          configMap:
            name: modoki-yamler-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: modoki-yamler-config
  namespace: modoki
data:
  yamler.yaml: |
    app_secret_name: modoki-apps-cert-secret
---
apiVersion: v1
kind: Service
metadata:
  name: modoki-yamler-svc
  namespace: modoki
spec:
  selector:
    app: modoki-yamler
  ports:
    - name: grpc-main
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: modoki-yamler-sa
  namespace: modoki
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: modoki-yamler-crb
subjects:
  - kind: ServiceAccount
    name: modoki-yamler-sa
    namespace: modoki
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
