name: Docker

on:
  push:
  pull_request:
    branches: [master]

jobs:
  apiserver:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image for API Server
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: modokipaas/modoki-k8s
          dockerfile: Dockerfile-api
          tag_with_ref: true
          tag_with_sha: true

  authserver:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image for Auth Server
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: modokipaas/modoki-auth
          dockerfile: Dockerfile-auth
          tag_with_ref: true
          tag_with_sha: true

  yamler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image for YAMLer
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: modokipaas/modoki-yamler
          dockerfile: Dockerfile-yamler
          tag_with_ref: true
          tag_with_sha: true

  manifests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      - name: Kustomize build
        run: |
          ./kustomize build ./kubernetes > /tmp/modoki.yaml

      - name: Upload modoki.yaml
        uses: actions/upload-artifact@v1
        with:
          name: Kubernetes manifests for modoki installation
          path: /tmp/modoki.yaml
